version: '3'
services:
  app:
    container_name: app
    build: .
    ports:
     - "3008:3008"
    volumes:
     - ./logs:/logs
    links:
      - mongo
    environment:
      - 'MONGODB=mongodb://mongo:27017/'
  mongo:
    container_name: mongo
    image: "mongo"
    ports:
     - "27030:27017"
